#baseURL = 'https://tech.hamstudy.org/'
languageCode = 'en-us'
title = 'HamStudy Technician License HamBook'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
math = true

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]